-- 1. Profiles Table (linked to Supabase auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null,
  phone text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Drop existing policies if they exist to avoid duplication errors
drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;

create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Automatic profile creator trigger upon authentication signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'phone', '')
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop existing trigger if it exists
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Quotes Table
create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  budget text not null,
  details text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.quotes enable row level security;

drop policy if exists "Anyone can submit quotes" on public.quotes;
drop policy if exists "Users can read their own quotes" on public.quotes;

create policy "Anyone can submit quotes" on public.quotes
  for insert with check (true);

create policy "Users can read their own quotes" on public.quotes
  for select using (auth.uid() = user_id);


-- 3. Cart Proposals Table
create table if not exists public.cart_proposals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  note text,
  items jsonb not null,
  total_estimated_price numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.cart_proposals enable row level security;

drop policy if exists "Anyone can submit cart proposals" on public.cart_proposals;
drop policy if exists "Users can view their own cart proposals" on public.cart_proposals;

create policy "Anyone can submit cart proposals" on public.cart_proposals
  for insert with check (true);

create policy "Users can view their own cart proposals" on public.cart_proposals
  for select using (auth.uid() = user_id);


-- 4. Projects (Order Tracking) Table
create table if not exists public.projects (
  id text primary key, -- e.g. 'BM-101'
  user_id uuid references auth.users on delete set null,
  service text not null,
  customer text not null,
  status_step integer not null default 1,
  last_update text not null,
  timeline jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;

drop policy if exists "Anyone can track by ID" on public.projects;

-- Read access is open for matching IDs (since visitors track order ID without signing in)
create policy "Anyone can track by ID" on public.projects
  for select using (true);


-- 5. Seed Data for Order Tracking
insert into public.projects (id, service, customer, status_step, last_update, timeline)
values 
('BM-101', 'Business Website Development', 'FreshMart', 5, 'Project completed and domain linked to server.', '[
  {"name": "Blueprint Confirmed", "date": "Jun 12", "done": true},
  {"name": "UI/UX Wireframing", "date": "Jun 15", "done": true},
  {"name": "Core Engineering", "date": "Jun 22", "done": true},
  {"name": "Quality Testing", "date": "Jun 26", "done": true},
  {"name": "Live Launch", "date": "Jun 28", "done": true}
]'),
('BM-202', 'E-commerce Website & Payment Integration', 'Smile Dental Clinic', 3, 'Payment gateway API keys connected. Starting admin dashboard layout.', '[
  {"name": "Blueprint Confirmed", "date": "Jun 18", "done": true},
  {"name": "UI/UX Wireframing", "date": "Jun 22", "done": true},
  {"name": "Core Engineering", "date": "In Progress", "done": "active"},
  {"name": "Quality Testing", "date": "Pending", "done": false},
  {"name": "Live Launch", "date": "Pending", "done": false}
]'),
('BM-303', 'Local Business GMB & Citation Boost', 'Aura Builders', 2, 'Google Maps listings submitted. Awaiting postcard verification.', '[
  {"name": "Blueprint Confirmed", "date": "Jun 28", "done": true},
  {"name": "Profile Optimization", "date": "In Progress", "done": "active"},
  {"name": "Citation Building", "date": "Pending", "done": false},
  {"name": "Verification & Review Setup", "date": "Pending", "done": false},
  {"name": "Live Listing", "date": "Pending", "done": false}
]')
on conflict (id) do nothing;
